---
rule-providers:
  RP-Direct:
    type: file
    behavior: classical
    path: "./direct.yaml"
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/rule_provider/direct.yaml
    interval: 86400
  RP-Gaming:
    type: file
    behavior: classical
    path: "./gaming.yaml"
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/rule_provider/direct.yaml
    interval: 86400
  RP-Reject:
    type: file
    behavior: classical
    path: "./reject.yaml"
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/rule_provider/direct.yaml
    interval: 86400
  RP-Sosmed:
    type: file
    behavior: classical
    path: "./sosmed.yaml"
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/rule_provider/direct.yaml
    interval: 86400
  RP-Streaming:
    type: file
    behavior: classical
    path: "./streaming.yaml"
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/rule_provider/direct.yaml
    interval: 86400
    
proxy-groups:
  - name: 🚀 GUniversal
    type: url-test
    disable-udp: false
    use:
    - PUniversal
    url: http://www.gstatic.com/generate_204
    interval: 180
    lazy: true
    
  - name: 🚀 GGame
    type: url-test
    disable-udp: false
    use:
    - PGame
    url: http://www.gstatic.com/generate_204
    interval: 180
    lazy: true
    
  - name: 🚀 GLoadBalance
    type: load-balance
    strategy: consistent-hashing
    disable-udp: false
    proxies:
    - 🚀 GUniversal
    - 🚀 GGame
    - 🚀 GSosmed
    - 🚀 GStream
    url: http://www.gstatic.com/generate_204
    interval: 300
    
  - name: 🚀 GSosmed
    type: select
    disable-udp: false
    use:
    - PSosmed
    filter: 'sosmed'
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: 🚀 GStream
    type: select
    disable-udp: false
    use:
    - PStream
    filter: 'streaming'
proxy-providers:
  PUniversal:
    type: http
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/proxy_provider/Universal.yaml
    path: "./Universal.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  PGame:
    type: http
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/proxy_provider/Game.yaml
    path: "./Game.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  PSosmed:
    type: http
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/proxy_provider/Sosmed.yaml
    path: "./Sosmed.yaml"
    filter: sosmed
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  PStream:
    type: http
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/proxy_provider/Stream.yaml
    path: "./Stream.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
      
dns:
  enable: true
  use-hosts: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:6868
  default-nameserver:
    - 119.29.29.29
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - tls://223.5.5.5:853
  fallback:
    - 'https://1.0.0.1/dns-query'  # append the proxy adapter name or group name to the end of DNS URL with '#' prefix.
    - 'tls://8.8.4.4:853'
  fallback-filter:
    geoip: false
    geosite:
      - gfw  # `geosite` filter only use fallback server to resolve ip, prevent DNS leaks to unsafe DNS providers.
    domain:
      - +.example.com
    ipcidr:
      - 0.0.0.0/32
      
# Enable the TUN listener
tun:
  enable: true
  stack: gvisor #  only gvisor
  dns-hijack: 
    - 0.0.0.0:53 # additional dns server listen on TUN
  auto-route: true # auto set global route
  
rules:

  # network(tcp/udp) condition for all rules
  - DOMAIN-SUFFIX,bilibili.com,DIRECT,tcp
  - DOMAIN-SUFFIX,bilibili.com,REJECT,udp
    
  # multiport condition for rules SRC-PORT and DST-PORT
  - DST-PORT,123/136/137-139,DIRECT,udp
  
  # rule GEOSITE
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,icloud@cn,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,facebook,PROXY
  - GEOSITE,youtube,PROXY
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
    
  # source IPCIDR condition for all rules in gateway proxy
  #- GEOSITE,geolocation-!cn,REJECT,192.168.1.88/32,192.168.1.99/32

  - GEOIP,telegram,PROXY,no-resolve
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  
  - MATCH,PROXY