---
rule-providers:
  RP-Direct:
    type: file
    behavior: classical
    path: "./direct.yaml"
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/rule_provider/direct.yaml
    interval: 86400
  RP-Gaming:
    type: file
    behavior: classical
    path: "./gaming.yaml"
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/rule_provider/direct.yaml
    interval: 86400
  RP-Reject:
    type: file
    behavior: classical
    path: "./reject.yaml"
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/rule_provider/direct.yaml
    interval: 86400
  RP-Sosmed:
    type: file
    behavior: classical
    path: "./sosmed.yaml"
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/rule_provider/direct.yaml
    interval: 86400
  RP-Streaming:
    type: file
    behavior: classical
    path: "./streaming.yaml"
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/rule_provider/direct.yaml
    interval: 86400
    
proxy-groups:
  - name: GUniversal
    type: url-test
    disable-udp: false
    use:
    - PUniversal
    url: http://www.gstatic.com/generate_204
    interval: '300'
    tolerance: '150'
  - name: GGame
    type: url-test
    disable-udp: false
    use:
    - PGame
    url: http://www.gstatic.com/generate_204
    interval: '300'
    tolerance: '150'
  - name: GLoadBalance
    type: load-balance
    strategy: consistent-hashing
    disable-udp: false
    proxies:
    - GUniversal
    - GGame
    - GSosmedOne
    - GStream
    url: http://www.gstatic.com/generate_204
    interval: '300'
  - name: GSosmedOne
    type: select
    disable-udp: false
    use:
    - PSosmed
    url: http://www.gstatic.com/generate_204
    interval: '300'
  - name: GStream
    type: select
    disable-udp: false
    use:
    - PStream
    
proxy-providers:
  PUniversal:
    type: http
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/proxy_provider/Universal.yaml
    path: "./Universal.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  PGame:
    type: http
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/proxy_provider/Game.yaml
    path: "./Game.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  PSosmed:
    type: http
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/proxy_provider/Sosmed.yaml
    path: "./Sosmed.yaml"
    filter: sosmed
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  PStream:
    type: http
    url: https://raw.githubusercontent.com/izhalakbar/PROJECT/main/AndoClash/proxy_provider/Stream.yaml
    path: "./Stream.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
      
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "+.*"
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 192.168.151.108
    - 119.29.29.29
    - 114.114.114.114
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 192.168.151.108
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - https://doh.pub/dns-query
    - tls://223.5.5.5:853
    - https://dns.adguard.com/dns-query
    - https://dns-google.com/dns-query
    - tls://dns.adguard.com
    - tls://dns-google.com/
    - https://dns.google/dns-query
    - tls://dns.google

rules:
  - DST-PORT,7895,REJECT
  - DST-PORT,7892,REJECT
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - RULE-SET,RP-Direct,DIRECT
  - RULE-SET,RP-Reject,REJECT
  - MATCH,GLOBAL
      
